#include "configuration.h"
#include "Audio.h"
#include "Timers.h"

const u16 TETRIS_THEME_KEYS[58] = {
   // part 1
  NOTE_E5, NOTE_B4, NOTE_C5, NOTE_D5, NOTE_C5, NOTE_B4, NOTE_A4, NOTE_A4, NOTE_C5, NOTE_E5, NOTE_D5, NOTE_C5, NOTE_B4, NOTE_B4, NOTE_C5, NOTE_D5, NOTE_E5, NOTE_C5, NOTE_A4, NOTE_A4, NONE,
  NOTE_D5, NOTE_F5, NOTE_A5, NOTE_G5, NOTE_F5, NOTE_E5, NOTE_C5, NOTE_E5, NOTE_D5, NOTE_C5, NOTE_B4, NOTE_B4, NOTE_C5, NOTE_D5, NOTE_E5, NOTE_C5, NOTE_A4, NOTE_A4, NONE,

  // part 2
  NOTE_E4, NOTE_C4, NOTE_D4, NOTE_B3, NOTE_C4, NOTE_A3, NOTE_G3_SHARP, NOTE_B3,
  NOTE_E4, NOTE_C4, NOTE_D4, NOTE_B3, NOTE_C4, NOTE_E4, NOTE_A4, NOTE_A4, NOTE_G4_SHARP, NONE
};

const u16 TETRIS_THEME_LENGTHS[58] = {
  // part 1
  HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE, HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE, HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE, HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE, HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE, HALF_NOTE, HALF_NOTE, HALF_NOTE, HALF_NOTE, HALF_NOTE, HALF_NOTE,
  HALF_NOTE+QUARTER_NOTE, QUARTER_NOTE, HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE, HALF_NOTE+QUARTER_NOTE, QUARTER_NOTE, HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE, HALF_NOTE, QUARTER_NOTE, QUARTER_NOTE, HALF_NOTE, HALF_NOTE, HALF_NOTE, HALF_NOTE, HALF_NOTE, HALF_NOTE,

  // part 2
  FULL_NOTE, FULL_NOTE, FULL_NOTE, FULL_NOTE, FULL_NOTE, FULL_NOTE, FULL_NOTE, FULL_NOTE,
  FULL_NOTE, FULL_NOTE, FULL_NOTE, FULL_NOTE, HALF_NOTE, HALF_NOTE, HALF_NOTE, HALF_NOTE, HALF_NOTE*3, HALF_NOTE
};

static uint8_t note_counter;
static Timer* audioTimer; 
void Audio_Initialize()
{
    note_counter = 0;
    audioTimer = timer_create(1);
    timer_start(audioTimer);
}
void Audio_RunActiveState()
{
    if(timer_ready(audioTimer))
    {
        PWMAudioSetFrequency(BUZZER1, TETRIS_THEME_KEYS[note_counter]);
        audioTimer->reference = TETRIS_THEME_LENGTHS[note_counter]; 
        note_counter= ((note_counter+1) % 58);
        timer_reset(audioTimer);
        PWMAudioOn(BUZZER1);
    }
}